model_name: Qwen/Qwen2.5-32B-Instruct
model_config: Qwen25Config32B
nodes: 8
ntasks_per_node: 1
gpus_per_node: 4
strategy:
  tensor_model_parallel_size: 4
  pipeline_model_parallel_size: 4
  context_parallel_size: 4
  sequence_parallel: True

trainer:
  devices: auto
  accelerator: gpu
  log_every_n_steps: 1
  limit_val_batches: 0
  val_check_interval: 0
  num_sanity_val_steps: 0

logger:
  save_last: true
  every_n_train_steps: 100
  monitor: reduced_train_loss
  save_top_k: 1
  save_on_train_epoch_end: true
  save_optim_on_train_end: true

optimizer:
  optimizer: adam
  lr: 0.00001
  adam_beta1: 0.9
  adam_beta2: 0.95
  weight_decay: 0.0001
  use_distributed_optimizer: true
  clip_grad: 1.0
  bf16: true

datamodule:
  seq_length: 32768
  micro_batch_size: 1
  global_batch_size: 16
  num_workers: 8