llm_kind: "openai_instruct"
llm_config:
  model_name: ""
  api_key: "None"
  generation_parameters:
    temperature: 0.6
    max_tokens: 512
    stop:
      - "</search>"
      - "</script>"
      - "</have>"
tools:
  have: {}
  search: {}
  script: {}
max_retry:
  search: 2
  have: 16
  script: 32
