llm_kind: "openai_instruct"
prompt_path: "export/dataset/prompt.json"
llm_config:
  model_name: "/lustre/fsn1/projects/rech/tdm/commun/models/crrrocq_compress/"
  api_key: "None"
  generation_parameters:
    temperature: 0.7
    max_tokens: 2048
    stop:
      - "</search>"
      - "</script>"
      - "</have>"
tools:
  have: {}
  search: {}
  script: {}
max_retry:
  search: 2
  have: 32
  script: 32
max_depth: 128